# Generated by Django 5.0.6 on 2024-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Şərh'),
        ),
    ]
